name: server workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: backend
      - name: Install dependencies
        run: ls
    #     run: pip install -r requirements.txt
    #   - name: Run Application
    #     run: python main.py
